import React from 'react';
import ReactDOM, { createRoot } from 'react-dom/client';
import './index.css';
import App from './App';
import CountClick from './Components/CountClick';
import LogInForm from './Components/MainComp';
import HelloRun from './Components/HelloRun';
const container = document.getElementById('root');
const root = createRoot(container);
root.render(<App />);
