import React from 'react';
import './index.css';
import App from './App';
import {createRoot} from 'react-dom/client';
import HelloFunctionComp from './Components/HelloFunctionComp';
import FormFc from './Components/FormFC';
import HelloCC from './Components/HelloCC';
const container = document.getElementById('root');
const root = createRoot(container);
root.render(<HelloCC person="Nam"/>);